### ISSUE TITLE
⚡ Node-MySql Implementation: 

### ISSUE THREAD

**Issue by meerhamzadev** [Open-Source-Society-PK/NodeJS-Applications#1]
Hey Saad 👋, Hope you are doing well. I have gone through this repository, and as it contains a variety of different Nodejs Implementations and boiler-plate codes which's quite great but It does not contain the boiler-plate/starter code of Nodejs with MySQL, and if allowed I would like to contribute this code.

Regards,
Meer Hamza

**Comment by saadhaxxan** [comment]
@MeerHamza1421 Yes definitely it will be really great.

**Comment by meerhamzadev** [comment]
Raised the pull request. Hope this would help.

**Comment by saadhaxxan** [comment]
Merged.
